
CREATE TABLE VENDOR_CHECK
(
	VENDOR_CHECK_ID NUMERIC(16) NOT NULL PRIMARY KEY,
	TYPE_OF_CHAR CHAR(3),
	TYPE_OF_CHAR_FOR_BIT_DATA CHAR(3) FOR BIT DATA,
	TYPE_OF_VARCHAR VARCHAR(32),
	TYPE_OF_VARCHAR_FOR_BIT_DATA VARCHAR(32) FOR BIT DATA,
	TYPE_OF_CLOB CLOB,
	TYPE_OF_DBCLOB DBCLOB,
	TYPE_OF_DECIMAL_DECIMAL DECIMAL(5, 3),
	TYPE_OF_DECIMAL_INTEGER DECIMAL(5, 0),
	TYPE_OF_DECIMAL_BIGINT DECIMAL(12, 0),
	TYPE_OF_SMALLINT SMALLINT,
	TYPE_OF_INTEGER INTEGER,
	TYPE_OF_BIGINT BIGINT,
	TYPE_OF_FLOAT FLOAT,
	TYPE_OF_DOUBLE DOUBLE,
	TYPE_OF_REAL REAL,
	TYPE_OF_DATE DATE,
	TYPE_OF_TIME TIME,
	TYPE_OF_TIMESTAMP TIMESTAMP,
	TYPE_OF_BLOB BLOB,
	TYPE_OF_GRAPHIC GRAPHIC,
	TYPE_OF_VARGRAPHIC VARGRAPHIC(32),
	TYPE_OF_LONG_VARGRAPHIC LONG VARGRAPHIC
)  ;
