
CREATE ALIAS ALIAS_MEMBER FOR MEMBER ;
CREATE ALIAS ALIAS_MEMBER_LOGIN FOR MEMBER_LOGIN ;

CREATE ALIAS ALIAS_EXCEPT FOR WHITE_EXCEPT;
CREATE ALIAS ALIAS_REF_EXCEPT FOR WHITE_REF_EXCEPT;
CREATE ALIAS ALIAS_TARGET FOR WHITE_TARGET;
CREATE ALIAS ALIAS_REF_TARGET FOR WHITE_REF_TARGET;
