
CREATE SEQUENCE SEQ_PURCHASE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MEMBER START WITH 1 INCREMENT BY 5;
CREATE SEQUENCE SEQ_MEMBER_ADDRESS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MEMBER_LOGIN START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRODUCT START WITH 1 INCREMENT BY 1;

