
CREATE TABLE VENDOR_CHECK (
	VENDOR_CHECK_ID NUMERIC(16) NOT NULL PRIMARY KEY,
	TYPE_OF_VARCHAR varchar(32),
	TYPE_OF_NVARCHAR nvarchar(32),
	TYPE_OF_TEXT text,
	TYPE_OF_NUMERIC_DECIMAL numeric(5, 3),
	TYPE_OF_NUMERIC_INTEGER numeric(5, 0),
	TYPE_OF_NUMERIC_BIGINT numeric(12, 0),
	TYPE_OF_SMALLINTEGER smallint,
	TYPE_OF_INTEGER integer,
	TYPE_OF_BIGINT bigint,
	TYPE_OF_MONEY money,
	TYPE_OF_SMALLMONEY smallmoney,
	TYPE_OF_DATETIME datetime,
	TYPE_OF_SMALLDATETIME smalldatetime,
	TYPE_OF_BIT bit,
	TYPE_OF_BINARY binary(2000),
	TYPE_OF_VARBINARY varbinary(2000),
	TYPE_OF_UNIQUEIDENTIFIER uniqueidentifier,
	TYPE_OF_XML xml
)  ;
